### ISSUE TITLE
大佬，安装都不能，全是安装失败

### ISSUE THREAD

**Issue by kanakey** [firesunCN/WechatEnhancement#2]
安卓5.0、6.0、MIUI全部都是安装失败，咋整啊

**Comment by dicksonlim0226** [comment]
我的也是安装失败。是不是x86的问题？？
我是Asus ZenFone 2 ZE551ML

**Comment by kanakey** [comment]
我两台机子，一台86一台64都不行

**Comment by kanakey** [comment]
原来是没签名，真操蛋，现在好了

**Comment by firesunCN** [comment]
release的都是签名的，你们是自己编译的么？

**Comment by kanakey** [comment]
不是啊，从xposed那里下载的，两个版本都安装失败

**Comment by firesunCN** [comment]
不应该啊 我这两个测试机都正常 我晚上在看一下

**Comment by firesunCN** [comment]
我知道原因 我回去重发布，我release的时候只勾了v2签名，android7以下都会安不了

**Comment by firesunCN** [comment]
@kanakey @dicksonlim0226 最新1.2.0已修复无法安装的bug
@kanakey 把选项关了重开，然后重启微信

**Comment by kanakey** [comment]
屏蔽广告是用的微信巫师的方法吧，它本身就屏蔽不了

**Comment by firesunCN** [comment]
@kanakey 对 用巫师的方法，巫师用的是xml解析后去除广告，所以其实还是会在朋友圈看到广告，但是把微信杀掉重开，重新解析xml后广告就消失了，确实需要改进一下

**Comment by kanakey** [comment]
期待大佬改进，要是能支持6.5.23就好了，6.6开始太卡了
