### ISSUE TITLE
屏幕闪烁的问题

### ISSUE THREAD

**Issue by cs50Mu** [firesunCN/WechatEnhancement#23]
在“发现”和“我”Tab界面，点击任何一个子Tab进入，界面会闪烁一下。。 没装插件之前貌似不会这样。

我是通过VirtualXposed使用WechatEnhancement的

另外，顺带问个问题，之前的微信聊天记录要如何才能迁移到新的里面？

**Comment by firesunCN** [comment]
建议都卸载了在测试一下，自测没问题
之前聊天记录可以使用电脑版微信的聊天记录备份功能
