### ISSUE TITLE
微信添加插件后没效果!

### ISSUE THREAD

**Issue by HB30hz** [firesunCN/WechatEnhancement#29]

**Comment by damao2017** [comment]
@firesunCN 作者大大你好，我的手机也不起作用，防撤回还是被撤回了。
华为mate9 电信版
安卓 8.0.0
微信版本 6.6.7 
VXP版本 0.11.5
微信增强 1.6.0

**Comment by damao2017** [comment]
关闭保守模式后重启一下框架，就起作用了
