### ISSUE TITLE
朋友圈防撤回功能需要完善

### ISSUE THREAD

**Issue by woshipachong** [firesunCN/WechatEnhancement#3]
测试发现，如果删除前没有打开朋友圈刷新，则删除后再打开朋友较，是看不到已删除的内容的

**Comment by firesunCN** [comment]
这个没法做到，因为如果在刷新前就删除了，根本无法从服务器获得这个数据，所以看没法看到，如果要解决需要让微信不断刷新这样会非常费电

**Comment by woshipachong** [comment]
好的，辛苦啦！

2018-04-13 

pachongxiao 



发件人：火日攻天@firesun <notifications@github.com>
发送时间：2018-04-12 19:05
主题：Re: [firesunCN/WechatEnhancement] 朋友圈防撤回功能需要完善 (#3)
收件人："firesunCN/WechatEnhancement"<WechatEnhancement@noreply.github.com>
抄送："woshipachong"<pachongxiao@126.com>,"Author"<author@noreply.github.com>

这个没法做到，因为如果在刷新前就删除了，根本无法从服务器获得这个数据，所以看没法看到，如果要解决需要让微信不断刷新这样会非常费电
