### ISSUE TITLE
微信6.7.3 play 商店版中撤回有bug

### ISSUE THREAD

**Issue by Takwah** [firesunCN/WechatEnhancement#39]
撤回自己的消息也会被阻止，尝试修复无果。

**Comment by Creamliu** [comment]
而且又一直防撤回，直到再次发送一条消息，严重的bug

**Comment by firesunCN** [comment]
目前靠以下代码过滤，是不是play版本的提示和官网下载的提示不一样，你们自己撤回的时候提示“你撤回了一条消息”吗？

contentValues.getAsInteger("type") == 10000 &&
!contentValues.getAsString("content").equals("你撤回了一条消息") &&
!contentValues.getAsString("content").equals("You've recalled a message")

**Comment by firesunCN** [comment]
应该修复了，可以再试下
