### ISSUE TITLE
朋友圈突破九张照片限制失效

### ISSUE THREAD

**Issue by yz41** [firesunCN/WechatEnhancement#68]
选出了10几张，测试了几次，发出去后几分钟会自动变成九张，后面几张不见了，没变成九张之前不能点赞和评论，好像还没上传的样子，华为荣耀10，安卓9.0，太极阴，微信7.03，模块版本1.9.0

**Comment by firesunCN** [comment]
本来就不支持发朋友圈突破9张
在聊天发图片的时候能突破9张
